### ISSUE TITLE
config paths

### ISSUE THREAD

**Issue by sam-motamed** [PhysGame/PhysGame#1]
Thanks for the great work, looking forward to trying it out. Just a comment on dependencies and config paths. There are a few files that are not mentioned in the installation guide and are pointed to as ```/home/thr/code/S3...```. would be great if these are added to the installation guide 😃

**Comment by sam-motamed** [comment]
followup: I am also getting a CUDA out of memory error with a 24 GB rtx 3090. Is this normal for running the gradio demo?

**Comment by PhysGame** [comment]
Sorry for the confusion and thanks for your feedback, that is the link I forgot to clean XD. For config paths, you need to download llava-hf/llava-onevision-qwen2-7b-si-hf and google/siglip-so400m-patch14-384. For memory consumption, unfortunately, now for inference, our model may take up to 40G memory and we will try to make it smaller, we recommend testing with lower frame input, maybe 16 is suitable for your case.

**Comment by sam-motamed** [comment]
Thanks for the suggestion. That is what I am just trying and the PhysVLM answer is ```PhysVLM answer: ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((("``` Any ideas on this?

**Comment by PhysGame** [comment]
That is because of the pytorch versiion is not suitable for Qwen-2 as we have met the same problem before we use torch==2.1.2

**Comment by sam-motamed** [comment]
Gotcha! thanks, will try that fix

**Comment by PhysGame** [comment]
update: you can modify the precision from fp16 to bf16 (in both config and demo_gradio.py) and this will save you a lot of memory (as we tested the demo on 32G V100 which did not support bf)
